# Generated by Django 5.0.6 on 2024-07-15 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=999)),
                ('authors', models.TextField(help_text='Comma separated list of authors')),
                ('journal', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('issue', models.IntegerField(blank=True, null=True)),
                ('pages', models.CharField(max_length=50)),
                ('doi', models.URLField(validators=[django.core.validators.URLValidator()])),
            ],
        ),
    ]
