# Generated by Django 5.0.6 on 2024-07-19 05:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Journal', 'Journal'), ('Protocol', 'Protocol'), ('Patent', 'Patent'), ('Dissertation', 'Dissertation')], default='Journal', max_length=13)),
                ('title', models.CharField(max_length=999)),
                ('authors', models.TextField(help_text='Comma separated list of authors')),
                ('year', models.PositiveIntegerField()),
                ('journal', models.CharField(max_length=255)),
                ('volume', models.PositiveIntegerField(blank=True, null=True)),
                ('issue', models.PositiveIntegerField(blank=True, null=True)),
                ('pages', models.CharField(blank=True, max_length=50, null=True)),
                ('doi', models.URLField(validators=[django.core.validators.URLValidator()])),
            ],
        ),
    ]
