# Generated by Django 5.0.6 on 2024-07-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-year']},
        ),
        migrations.AddField(
            model_name='publication',
            name='month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
