# Generated by Django 5.0.6 on 2024-07-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='pages',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
