# Generated by Django 5.0.6 on 2024-07-23 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_alter_publication_options_publication_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-year', '-month']},
        ),
    ]
