# Generated by Django 5.0.6 on 2024-07-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_alter_publication_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='type',
            field=models.CharField(blank=True, choices=[('Journal', 'Journal'), ('Protocol', 'Protocol'), ('Patent', 'Patent')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='issue',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='volume',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
