# Generated by Django 5.0.6 on 2024-07-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_publication_type_alter_publication_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(blank=True, choices=[('Journal', 'Journal'), ('Protocol', 'Protocol'), ('Patent', 'Patent'), ('Dissertation', 'Dissertation')], max_length=13, null=True),
        ),
    ]
