# Generated by Django 5.0.6 on 2024-07-19 04:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=50)),
                ('year_start', models.PositiveIntegerField()),
                ('year_finish', models.PositiveIntegerField(blank=True, null=True)),
                ('doctor_degree', models.CharField(blank=True, max_length=5, null=True)),
                ('doctor_school', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor_earned_year', models.PositiveIntegerField(blank=True, null=True)),
                ('master_degree', models.CharField(blank=True, max_length=5, null=True)),
                ('master_school', models.CharField(blank=True, max_length=100, null=True)),
                ('master_earned_year', models.PositiveIntegerField(blank=True, null=True)),
                ('bachelor_degree', models.CharField(blank=True, max_length=5, null=True)),
                ('bachelor_school', models.CharField(blank=True, max_length=100, null=True)),
                ('bachelor_earned_year', models.PositiveIntegerField(blank=True, null=True)),
                ('google_scholar', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('orcid', models.CharField(blank=True, max_length=19, null=True)),
                ('linkedin', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
            ],
        ),
    ]
