# Generated by Django 5.0.6 on 2024-07-23 03:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=50)),
                ('year_start', models.PositiveIntegerField()),
                ('year_finish', models.PositiveIntegerField(blank=True, null=True)),
                ('google_scholar', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('orcid', models.CharField(blank=True, max_length=19, null=True)),
                ('linkedin', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('pubmed', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, max_length=5, null=True)),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('year_earned', models.PositiveIntegerField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='people.person')),
            ],
        ),
    ]
