# Generated by Django 5.0.6 on 2024-07-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_personal_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='priority',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'supervisor'), (2, 'postdoc'), (3, 'grad student'), (4, 'staff')], null=True),
        ),
    ]
