# Generated by Django 5.0.6 on 2024-07-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_person_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
        migrations.AddField(
            model_name='person',
            name='position_after_finish',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
