# Generated by Django 5.1 on 2025-05-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_person_options_person_position_after_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='priority',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'supervisor'), (2, 'postdoc'), (3, 'grad student'), (4, 'staff'), (5, 'undergrad')], null=True),
        ),
    ]
