# Generated by Django 5.2 on 2026-04-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_alter_person_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='priority',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'supervisor'), (2, 'postdoc'), (3, 'visiting scholar'), (4, 'grad student'), (5, 'staff'), (6, 'undergrad')], null=True),
        ),
    ]
