# Generated by Django 5.0.6 on 2026-08-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_alter_person_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='priority',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'supervisor'), (2, 'postdoc'), (3, 'visiting scholar'), (4, 'grad student'), (5, 'research technician'), (6, 'undergrad')], null=True),
        ),
    ]
